services:
  mysql-hub:
    image: mysql:${TAG}
    container_name: mysql-hub
    environment:
      MYSQL_ROOT_PASSWORD: ${HUB_DB_PASSWORD}
      MYSQL_DATABASE: ${SYNC_DB}
    volumes:
      - ${HUB_DATA}:/var/lib/mysql
      - ${HUB_CONFIG}:/etc/mysql/conf.d
    ports:
      - "${HUB_DB_PORT}:3306"
    networks:
      - hub-net

  mysql-spoke:
    image: mysql:${TAG}
    container_name: mysql-spoke
    depends_on:
      - mysql-hub
    environment:
      MYSQL_ROOT_PASSWORD: ${SPOKE_DB_PASSWORD}
      MYSQL_DATABASE: ${SYNC_DB}
    volumes:
      - ${SPOKE_DATA}:/var/lib/mysql
      - ${SPOKE_CONFIG}:/etc/mysql/conf.d
    ports:
      - "${SPOKE_DB_PORT}:3306"
    networks:
      - hub-net

volumes:
  mysql-hub-data:
  mysql-spoke-data:

networks:
  hub-net:
    driver: bridge